version: '2'
services:
  flask:
    build: ./
    ports:
    - "80:80"
    - "443:443"
    volumes:
    - ./:/workdir
    - /etc/letsencrypt/live/bot.myshortreport.com/:/etc/letsencrypt/live/bot.myshortreport.com/